name: Node.js build and deployment workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  pack_validation:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: zip file compress
          run: zip -r webapp.zip .

        - name: Setup 'packer'
          uses: hashicorp/setup-packer@main
          id: setup
          with:
            version: "latest"

        - name: Run packer init
          id: init
          run: "packer init ."

        - name: Run packer validate
          id: validate
          run: "packer validate -var-file=var_pkr.pkrvars.hcl ."